pipeline:
  build:
    image: jekyll/jekyll:builder
    volumes:
      - /var/www/10000_schuerholz.it/bundle:/usr/local/bundle
    commands:
      - 'chown jekyll:jekyll .'
      - 'bundle install'
      - 'jekyll build'

  deploy:
    image: jekyll/jekyll:builder
    volumes:
      - /var/www/10000_schuerholz.it/htdocs:/srv/jekyll
      - /var/www/10000_schuerholz.it/bundle:/usr/local/bundle
    when:
      branch: master
    commands:
      - 'chown jekyll:jekyll .'
      - 'jekyll build'
      - 'rsync -vh -rz --links --checksum --delete _site/ /srv/jekyll'
  deploy:
    image: jekyll/jekyll:builder
    volumes:
      - /var/www/10000_schuerholz.it/devdocs:/srv/jekyll
      - /var/www/10000_schuerholz.it/bundle:/usr/local/bundle
    when:
      branch: develop
    commands:
      - 'chown jekyll:jekyll .'
      - 'jekyll build'
      - 'rsync -vh -rz --links --checksum --delete _site/ /srv/jekyll'
