title: Dennis Schürholz
subtitle: IT-Dienstleistungen
email: info@schuerholz.it
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://schuerholz.it"
social:
    user: ['Lebenslauf', 'https://www.dennisschuerholz.de']
    github: ['GitHub', 'http://github.com/dennisschuerholz']
#    twitter: ['Twitter', 'https://twitter.com/schuer_holz']
    linkedin: ['LinkedIn', 'https://www.linkedin.com/in/schuerholz/']
    xing: ['XING', 'https://www.xing.com/profile/Dennis_Schuerholz2']
    envelope: ['E&#8209;Mail', 'mailto:info@schuerholz.it']
style:
    {
        color: '#0094aa',
        font-family: 'Lato%3A400%2C300%2C700%7CPlayfair+Display'
    }
form:
    {
        token:          'b2721ffeb48cf6634c39d6177b682c66',
        successText:    '',
        caption:        '',
        button:         '',
        text:
            {
                name:   '',
                email:  '',
                topic:  '',
                text:   'Ihre Anfrage',
                submit: ''
            },
        placeholder:
            {
                name:   '',
                email:  '',
                topic:  '',
                text:   ''
            },
        topics:
            [
                'Allgemeine Kontaktaufnahme',
                'Webentwicklung',
                'Webhosting',
                'Technische Betreuung',
                'Netzwerk',
                'WLAN',
                'Schulung'
            ]
    }

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null
sass:
    load_paths:
        - _sass
        - bootstrap-4.0.0-alpha.6


# Handling Reading
safe:         false
include:      [".htaccess", "_pages"]
exclude:      ["Gemfile", "Gemfile.lock", "vendor/bundle", "*~", "*.zip", "wp-save.html", "wp-theme-readme.txt", "_pages/kundenstimmen.md", "_pages/ueber.md"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
#gems:      ["jekyll-feed"]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    '::'

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

defaults:
  -
    scope:
      path: _pages
    values:
      type: pages
      layout: default
      permalink: "/:title"

# compress-Layout
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
#  ignore:
#    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

